[phases.setup]
nixPkgs = ["php83", "php83Extensions.gd", "php83Extensions.pdo_mysql", "php83Extensions.mbstring", "php83Extensions.xml", "php83Extensions.bcmath", "php83Extensions.fileinfo", "php83Extensions.tokenizer", "php83Extensions.ctype", "php83Extensions.openssl"]

[phases.build]
cmds = ["composer install --no-dev --optimize-autoloader --ignore-platform-reqs"]
